version: "3"

services:
  phoenix:
    build: .
    # command: mix phx.server
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./src:/app
      - .:/workspace:cached
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: